name: data_viz
channels:
  - plotly
  - defaults
  - conda-forge
dependencies:
  - appnope=0.1.0
  - asn1crypto=0.24.0
  - attrs=19.1.0
  - autopep8=1.4.3
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - bokeh=1.1.0
  - ca-certificates=2019.1.23
  - certifi=2019.3.9
  - cffi=1.12.2
  - chardet=3.0.4
  - cryptography=2.6.1
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.5.0
  - entrypoints=0.3
  - expat=2.2.6
  - freetype=2.9.1
  - gettext=0.19.8.1
  - glib=2.56.2
  - googlemaps=2.5.1
  - icu=58.2
  - idna=2.8
  - intel-openmp=2019.3
  - ipykernel=5.1.0
  - ipython=7.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.3
  - jinja2=2.10.1
  - jpeg=9b
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - kiwisolver=1.0.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - libpng=1.6.36
  - libsodium=1.0.16
  - libtiff=4.0.10
  - markupsafe=1.1.1
  - matplotlib=3.0.3
  - mistune=0.8.4
  - mkl=2019.3
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - nbconvert=5.4.1
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=5.7.8
  - numpy=1.16.2
  - numpy-base=1.16.2
  - olefile=0.46
  - openssl=1.1.1b
  - packaging=19.0
  - pandas=0.24.2
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.4.0
  - patsy=0.5.1
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=5.4.1
  - pip=19.0.3
  - plotly=3.8.0
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - pycodestyle=2.5.0
  - pycparser=2.19
  - pygments=2.3.1
  - pyopenssl=19.0.0
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - pysocks=1.6.8
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pyyaml=5.1
  - pyzmq=18.0.0
  - qt=5.9.7
  - qtconsole=4.4.3
  - readline=7.0
  - requests=2.21.0
  - retrying=1.3.3
  - scikit-learn=0.20.3
  - scipy=1.2.1
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=41.0.0
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.27.2
  - statsmodels=0.9.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - tornado=6.0.2
  - traitlets=4.3.2
  - urllib3=1.24.1
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.1
  - widgetsnbextension=3.4.2
  - xlrd=1.2.0
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.3.7

